### ISSUE TITLE
ParserException: Unexpected character

### ISSUE THREAD

**Issue by ninfito** [renanbr/bibtex-parser#62]
Consider the next example: 

```php
<?php

use RenanBr\BibTexParser\Listener;
use RenanBr\BibTexParser\Parser;

require 'vendor/autoload.php';

$bibtex = <<<BIBTEX
@String{Andrasfai            = {Andr{\'{a}}sfai, B{\'{e}}la}}
@String{Bollobas             = {Bollob{\'{a}}s, B{\'{e}}la}}
@String{Chvatal              = {Chv{\'{a}}tal, Va{\v{s}}ek}}
@String{Erdos                = {Erd{\H{o}}s, Paul}}
@String{Gyarfas              = {Gy{\'{a}}rf{\'{a}}s, Andr{\'{a}}s}}
@String{Lovasz               = {Lov{\'{a}}sz, L{\'{a}}szl{\'{o}}}}
@String{Balbuena             = {Balbuena, Camino}}
@String{Cera                 = {Cera, Mart{\'{\i}}n}}
@String{Dianez               = {Di{\'{a}}nez, Ana}}
@String{Garcia-Vazquez       = {Garc{\'{\i}}a-V{\'{a}}zquez, Pedro}}

@Article{BCDGV07TopologicalFree,
  author    = Balbuena #{ and } # Cera #{ and } # Dianez #{ and } # Garcia-Vazquez,
  title     = {New exact values of the maximum size of graphs free of topological complete subgraphs},
  journal   = {Discrete Mathematics},
  year      = {2007},
  volume    = {307},
  number    = {9-10},
  pages     = {1038--1046},
  issn      = {0012-365X},
  doi       = {10.1016/j.disc.2006.07.031},
  keywords  = {Extremal graphs},
  publisher = {Elsevier {BV}},
  }
BIBTEX;
$parser = new Parser();          // Create a Parser
$listener = new Listener();      // Create and configure a Listener
$parser->addListener($listener); // Attach the Listener to the Parser
$parser->parseString($bibtex);   // or parseFile('/path/to/file.bib')
$entries = $listener->export();  // Get processed data from the Listener

print_r($entries);
?>
```
Which gives the following: 
```bash
PHP Fatal error:  Uncaught RenanBr\BibTexParser\Exception\ParserException: Unexpected character '-' at line 13 column 75 in ~/PHP/vendor/renanbr/bibtex-parser/src/Exception/ParserException.php:28
Stack trace:
#0 ~/PHP/vendor/renanbr/bibtex-parser/src/Parser.php(349): RenanBr\BibTexParser\Exception\ParserException::unexpectedCharacter(''-'', 13, 75)
#1 ~/PHP/vendor/renanbr/bibtex-parser/src/Parser.php(368): RenanBr\BibTexParser\Parser->readPreTagContent('-')
#2 ~/PHP/vendor/renanbr/bibtex-parser/src/Parser.php(185): RenanBr\BibTexParser\Parser->readRawTagContent('-')
#3 ~/PHP/vendor/renanbr/bibtex-parser/src/Parser.php(124): RenanBr\BibTexParser\Parser->read('-')
#4 ~/PHP/vendor/renanbr/bibtex-parser/src/Parser.php(112): RenanBr\BibTexParser\Parser->parse('@String{Andrasf...')
#5 ~/PHP/parserbib.php(37): RenanBr\BibTexParser\Parser->parseString('@String{Andrasf...')
#6 {main}
  thrown in ~/PHP/vendor/renanbr/bibtex-parser/src/Exception/ParserException.php on line 28
```
This seems to be caused by the character `-` in the string constant `Garcia-Vazquez`, created at line 10 of the bib-file:
```php
@String{Garcia-Vazquez       = {Garc{\'{\i}}a-V{\'{a}}zquez, Pedro}}
``` 
...and subsequently used in the `author` field at line 13. 

According to [this answer](https://tex.stackexchange.com/a/408548), only the characters  `" # ' ( ) , = { } %` should be banned in bib-keys, if possible.

According [this bibtex-summary](http://maverick.inria.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html#stringdef) the placeholder (variable/string name) must start with a letter and can contain any character in [A-Z,a-z,_,0-9]. In any case, the character `_` gives the same issue.

**Comment by renanbr** [comment]
Thanks for reporting this issue.

good catch

I think it could be fixed harmonising [tag name regex `/^[a-zA-Z0-9_\+:\-\.\/]$/`](https://github.com/renanbr/bibtex-parser/blob/master/src/Parser.php#L269) and [raw tag content regex `/^[a-zA-Z0-9]$/`](https://github.com/renanbr/bibtex-parser/blob/master/src/Parser.php#L362), because raw values may reference a tag content.
